name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Github Release
        uses: kbrashears5/github-action-release-maker@master
        with:
          VERSION: 1.0.17
          TOKEN: ${{ secrets.ACTIONS }}