name: CI/CD

on:
  push:
    branches:
      - master
      - main
    paths:
      - src/**
      - .github/**
  pull_request:
    branches:
      - master
      - main
    paths:
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use .NET Core 5.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          node-version: 5.0.x
          registry-url: https://api.nuget.org/v3/index.json
      - name: Install Dependencies
        run: dotnet restore
      - name: Build Package
        run: dotnet build
      - name: Test Code
        run: dotnet test
      - name: Create Package
        if: ${{ github.ref == 'refs/heads/master' }}
        run: dotnet pack
      # - name: Publish Package
      #   if: ${{ github.ref == 'refs/heads/master' }}
      #   run: dotnet nuget push
      #   env:
      #     NUGET_AUTH_TOKEN: ${{ secrets.NPM }}
  # release:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.ref == 'refs/heads/master' }}
  #   needs: build

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Get NPM Version
  #       id: package-version
  #       uses: martinbeentjes/npm-get-version-action@master
  #     - name: Github Release
  #       uses: kbrashears5/github-action-release-maker@master
  #       with:
  #         VERSION: ${{ steps.package-version.outputs.current-version}}
  #         TOKEN: ${{ secrets.ACTIONS }}
